### ISSUE TITLE
Simplify Even or Odd function to use ternary

### ISSUE THREAD

**Issue by mhaidarhanif** [reymondjulio/learn-javascript#2]
https://github.com/reymondjulio/learn-javascript/blob/2975404a16da3f68939cca1a800864feea741421/even-or-odd.js#L1-L7

**Comment by reymondjulio** [comment]
Finished simplifying even or odd functions to use ternary

https://github.com/reymondjulio/learn-javascript/blob/main/examples/even-or-odd.js
